Medical_analysis:
  outputs:
    dev:
      dbname: Tg_med
      host: localhost
      password: "1997"
      port: 5432
      schema: Raw
      threads: 1
      type: postgres
      user: postgres
  target: dev
med_insights:
  outputs:
    dev:
      dbname: Tg_med
      host: localhost
      pass: '1997'
      port: 5432
      schema: Raw
      threads: 1
      type: postgres
      user: postgres
  target: dev
